### ISSUE TITLE
1.9.4 - Problem

### ISSUE THREAD

**Issue by fede1132** [GamerKing195/Up2Date#12]
Hi, 

When i try to run Up2Date on my VPS (Mincraft Spigot Server 1.9.4) console is full with errors of any type.

GamerKing, can you fix this ?

**Comment by GamerKing195** [comment]
Hey there, this plugin only supports 1.10+ servers due to some of the protocol used frequently throughout the plugin, since you're using an outdated version I can't give any support apologies.
