### ISSUE TITLE
1.12 - Plugins Problems

### ISSUE THREAD

**Issue by fede1132** [GamerKing195/Up2Date#13]
Hi,

I have problem with Up2Date, i have upgraded my server to 1.12 and plugin throw error and can't found Plugins ID like this GIF: 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19489048/36639592-e0c12836-1a0f-11e8-908f-8ac2f8f39559.gif)
And like this [Log](https://paste.ee/p/HqCUJ).

**Comment by mmuziek** [comment]
hey there any plugin thats premium gives this problem with me.
im logged in so i do not know why

**Comment by GamerKing195** [comment]
@mmuziek could you please post any errors you receive while doing this along with any other information you have on the issue?

**Comment by mmuziek** [comment]
@GamerKing195 it seems to fix itself after 8 times restarting.
o and there where amost no errors

**Comment by GamerKing195** [comment]
Hey there, this issue should be fixed in version 1.4.3, found [here](https://www.spigotmc.org/resources/up2date.49313/update?update=228103). If the issue wasn't fixed here, feel free to reopen this issue. Thanks!
