### ISSUE TITLE
Bug when calling Update plugin info (right bottom button in gui)

### ISSUE THREAD

**Issue by mmuziek** [GamerKing195/Up2Date#15]
https://pastebin.com/S3HnWQmR
it keeps saying 0 of ... 
and do not do anything see link for error report

**Comment by GamerKing195** [comment]
Hey there this seems to be an issue with the login process, I'll be looking into overhauling this whole system but in the meantime I'm adding a system to reset and log in to spigot again which should fix this.

**Comment by GamerKing195** [comment]
Hey there, this issue should be fixed in version 1.4.3, found [here](https://www.spigotmc.org/resources/up2date.49313/update?update=228103). If the issue wasn't fixed here, feel free to reopen this issue. Thanks!
