### ISSUE TITLE
Updates do not always work?

### ISSUE THREAD

**Issue by mmuziek** [GamerKing195/Up2Date#17]
the plugin Reward pro reports itself if he finds an update aswell as your plugin.
sadly even when i force update it using u2d it keeps the old version if i download it manually from spigot (download button) its the correct version and doesnt show update anymore

**Comment by GamerKing195** [comment]
Hey there this issue is currently known, it seems to only be with a very select few plugins and I haven't been able to find a reason as to why. I would recommend unlinking them from up2date as theyre currently incompatible likely due to something on the author of reward pro but I might be able to figure something out.

**Comment by mmuziek** [comment]
hi there mabe its a suggestion to check the version of the downloaded jar and check if its the right version.
if not tell the user to try it again later

**Comment by GamerKing195** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - Certain plugins failing updates.](https://trello.com/c/mNPy2tLh/82-fix-certain-plugins-failing-updates)

**Comment by GamerKing195** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - Certain plugins failing updates.](https://trello.com/c/mNPy2tLh/82-fix-certain-plugins-failing-updates)

**Comment by GamerKing195** [comment]
Hey there, this issue should be fixed in version 1.4.3, found [here](https://www.spigotmc.org/resources/up2date.49313/update?update=228103). If the issue wasn't fixed here, feel free to reopen this issue. Thanks!
