### ISSUE TITLE
Gui glitches?

### ISSUE THREAD

**Issue by mmuziek** [GamerKing195/Up2Date#18]
the Gui glitches many times.
currently when you doubleclick to update it dupes the button in the inventory showing 2 instead of 1 item for that plugin.

**Comment by GamerKing195** [comment]
Hey there, this issue should be fixed in version 1.4.3, found [here](https://www.spigotmc.org/resources/up2date.49313/update?update=228103). If the issue wasn't fixed here, feel free to reopen this issue. Thanks!
