### ISSUE TITLE
Error in console?

### ISSUE THREAD

**Issue by mmuziek** [GamerKing195/Up2Date#20]
15.03 18:33:35 [Server] ERROR [U2D] ============== BEGIN ERROR ============== 15.03 18:33:35 [Server] ERROR [U2D] Error occurred while beginning automatic refresh. 15.03 18:33:35 [Server] ERROR [U2D] 15.03 18:33:35 [Server] ERROR [U2D] PLUGIN VERSION: V1.4.2 (LATEST) 15.03 18:33:35 [Server] ERROR [U2D] 15.03 18:33:35 [Server] ERROR [U2D] PLUGIN MESSAGE: HTTP Error while connecting to spigot. 15.03 18:33:35 [Server] INFO ERROR: Server returned HTTP response code: 403 for URL: https://spigotmc.org/ 15.03 18:33:35 [Server] INFO Please wait 120 minutes for another automatic refresh. 15.03 18:33:35 [Server] INFO If this error repeats please report it to the developer at https://github.com/GamerKing195/Up2Date/issues 15.03 18:33:35 [Server] INFO Or on spigot at https://spigotmc.org/threads/284883/ 15.03 18:33:35 [Server] ERROR [U2D] 15.03 18:33:35 [Server] ERROR [U2D] ============== END ERROR ==============

**Comment by GamerKing195** [comment]
Hey there, does this error repeat every 120 minutes?

**Comment by mmuziek** [comment]
yes it repeats every 120 minutes ( i set it to 2 hours to refesh)

**Comment by GamerKing195** [comment]
Hey there, this issue should be fixed in version 1.4.3, found [here](https://www.spigotmc.org/resources/up2date.49313/update?update=228103). If the issue wasn't fixed here, feel free to reopen this issue. Thanks!
