### ISSUE TITLE
Update all causes a BIG LOAD of errors

### ISSUE THREAD

**Issue by mmuziek** [GamerKing195/Up2Date#21]
here you go
https://pastebin.com/HtMTK12M

**Comment by GamerKing195** [comment]
Hey there, do you have discord? If so could you join the Up2Date discord [here](https://discord.gg/QmPHeFR) considering the influx of errors you've been having I think I'd be able to help better through the discord.

**Comment by GamerKing195** [comment]
Hey there, this issue should be fixed in version 1.4.3, found [here](https://www.spigotmc.org/resources/up2date.49313/update?update=228103). If the issue wasn't fixed here, feel free to reopen this issue. Thanks!
