### ISSUE TITLE
Severe Error During In-Game Setup

### ISSUE THREAD

**Issue by Centricks1** [GamerKing195/Up2Date#3]
Just bought the plugin and upon launching the in-game setup I get this error when attempting to download dependencies. 

`[Sun, 28. Jan 2018 15:25:45 CET ERROR] [U2D] ============== BEGIN ERROR ==============
[Sun, 28. Jan 2018 15:25:45 CET ERROR] [U2D] PLUGIN VERSION: Up2Date V1.2.3
[Sun, 28. Jan 2018 15:25:45 CET ERROR] [U2D] 
[Sun, 28. Jan 2018 15:25:45 CET ERROR] [U2D] PLUGIN MESSAGE: Error occurred while downloading dependencies.
[Sun, 28. Jan 2018 15:25:45 CET ERROR] [U2D] 
[Sun, 28. Jan 2018 15:25:45 CET ERROR] [U2D] MESSAGE: https://api.spiget.org/v2/resonew urces/39719/download
[Sun, 28. Jan 2018 15:25:45 CET ERROR] [U2D] 
[Sun, 28. Jan 2018 15:25:45 CET ERROR] [U2D] STACKTRACE: 
[Sun, 28. Jan 2018 15:25:45 CET WARN] java.io.FileNotFoundException: https://api.spiget.org/v2/resonew urces/39719/download
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at java.security.AccessController.doPrivileged(Native Method)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at com.gamerking195.dev.up2date.command.SetupCommand.downloadResources(SetupCommand.java:308)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at com.gamerking195.dev.up2date.command.SetupCommand.onCommand(SetupCommand.java:111)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at java.lang.Thread.run(Thread.java:748)
[Sun, 28. Jan 2018 15:25:45 CET WARN] Caused by: java.io.FileNotFoundException: https://api.spiget.org/v2/resonew urces/39719/download
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3000)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at java.net.URLConnection.getContentLength(URLConnection.java:485)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:407)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     at com.gamerking195.dev.up2date.command.SetupCommand.downloadResources(SetupCommand.java:306)
[Sun, 28. Jan 2018 15:25:45 CET WARN]     ... 17 more
[Sun, 28. Jan 2018 15:25:45 CET ERROR] [U2D]
[Sun, 28. Jan 2018 15:25:45 CET ERROR] [U2D] ============== END ERROR ==============`

![capture](https://user-images.githubusercontent.com/35894646/35483280-9333a5ee-0416-11e8-9014-36355cfa07bf.PNG)

**Comment by GamerKing195** [comment]
Hey there, I'll look into this and release a fix as soon as possible.

**Comment by GamerKing195** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - Invalid URL in setup](https://trello.com/c/m6Dnydnu/57-fix-invalid-url-in-setup)

**Comment by GamerKing195** [comment]
Hello there, I've released a fix for this bug that hopefully works as expected in version 1.2.4 found [here](https://www.spigotmc.org/resources/up2date.49313/update?update=208964). I'm going to close this issue for now but if this did not fix your issue please comment again and re-open the issue and I'll be happy to help further.
