### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by Centricks1** [GamerKing195/Up2Date#6]
During the set up, it crashes my server with this error:

![up2dateerror](https://user-images.githubusercontent.com/35894646/35495904-cc8ab980-0499-11e8-966c-2d962fc3bf10.png)

**Comment by GamerKing195** [comment]
Hey there, ill see if I have time to look into this tommorow. I apologize for the amount of bugs you're encountering with the plugin but it has a lot of moving parts and I couldn't test everything. However, I think that the plugin could be much more stable in the foreseeable future.

**Comment by GamerKing195** [comment]
Could you please provide the statistics of your server, RAM, CPU, etc
