### ISSUE TITLE
Infinite setup if invalid credentials

### ISSUE THREAD

**Issue by magemaniac33** [GamerKing195/Up2Date#7]
Essentially if you enter the wrong information or your 2FA resets while it's authenticating...
Well the credentials are already cached and even if you restart it does nothing.

I know if you delete the $MainDir/plugins/.creds folder and restart the server, it will fix it, however I believe it should tell you that it failed and have you re-login rather than just saying it in the action bar.

Sometimes it's a bit hard to read depending on everyone's MC, but I think it should output that it failed and have a yes/no if you'd like to try to login again.

**Comment by GamerKing195** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - Credentials caching on setup](https://trello.com/c/VkcFaYjR/62-fix-credentials-caching-on-setup)

**Comment by GamerKing195** [comment]
Hey there, I've got some time to look into this today but I'm not sure I understand what you're asking for. Could you elaborate on what you do in the setup (wrong information being the wrong username, password, or wrong 2fa key?) and what information is not being sent?

**Comment by GamerKing195** [comment]
Hey there, this issue should be fixed in version 1.4.3, found [here](https://www.spigotmc.org/resources/up2date.49313/update?update=228103). If the issue wasn't fixed here, feel free to reopen this issue. Thanks!
